name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          chmod +x ./scripts/workflowAWS.sh && \
          ./scripts/workflowAWS.sh \
          cert='${{ secrets.AWS_SSH_PEM }}' \
          user='${{ secrets.AWS_USER }}' \
          host='${{ secrets.AWS_HOST }}'