name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          echo "${{ secrets.AWS_SSH_PEM }}" > cert.pem && \
          chmod 400 cert.pem && \
          mkdir -p ~/.ssh/ && \
          chmod 700 ~/.ssh/ && \
          ssh-keyscan -H "${{ secrets.AWS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts && \
          ssh -i 'cert.pem' ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} 'echo "ola" > test.remote && pwd'