name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Step 3
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Step 4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      # Step 5
      - name: Build Application and Run unit Test
        run: python app.py & pytest
  CD:
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: guilherme-ferraz/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_AWS_EZOPS_TEST_GUILHERME }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS_AWS_EZOPS_TEST_GUILHERME }}
      - name: rsync over ssh
        run: ./scripts/deploy_to_aws.sh