name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create CodeDeploy Deployment
        id: deploy
        env:
          AWS_USER: ubuntu
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_SSH_PEM: ${{ secrets.AWS_SSH_PEM }}
        run: |
          chmod +x ./scripts/workflowAWS.sh && \
          ./scripts/workflowAWS.sh \
          cert='${{ env.AWS_SSH_PEM }}' \
          user='${{ env.AWS_USER }}' \
          host='${{ env.AWS_HOST }}'