name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create CodeDeploy Deployment
        id: deploy
        env:
          HOST: ${{ secrets.AWS_HOST }}
        shell: bash
        run: |
          echo "environment=production" > .env.production && \
          echo "host=$HOST" >> .env.production && \
          chmod +x ./scripts/workflowAWS.sh && \
          ./scripts/workflowAWS.sh \
          cert='${{ env.AWS_SSH_PEM }}' \
          user='${{ env.AWS_USER }}' \
          host='${{ secrets.AWS_HOST }}'