name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: executing remote ssh commands using password
        run: |
          whoami
          pwd
          ls -lah
           # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          echo "${{ secrets.AWS_SSH_PEM }}" > cert.pem && \
          cat cert.pem && \
          ssh -i 'cert.pem' ubuntu@ec2-54-232-137-215.sa-east-1.compute.amazonaws.com 'echo "ola" > test.remote && pwd'