name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: ./
        with:
          host: ${{ secrets.HOST_AWS_EZOPS_TEST_GUILHERME }}
          username: ${{ secrets.USER_AWS_EZOPS_TEST_GUILHERME }}
          key: ${{ secrets.SSH_AWS_EZOPS_TEST_GUILHERME }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            pwd
            ls -lah